### PR TITLE
infos for starting out, again

### PR DESCRIPTION
**Pull request by sup**
(accidentally deleted my fork so here we go again, ping @ashleygwilliams, @nebrius)

i had the idea that we might as well tell people where to start when wanting to contribute to the project. the lines i added are only a draft, feel free to correct my wording or something!

### CODE REVIEW

**Comment by sup** [comment]
suggestion: add me as a collaborator so stuff like this doesn't happen again and i can pr from a project-internal branch

**Comment by sup** [comment]
closing this since 1.0 is gonna be merged anyways

**Comment by ashleygwilliams** [comment]
hey @sup  i think this could be a great start to a CONTRIBUTING.md -- wanna start that? @zkat was interested in having one of those as well

**Comment by sup** [comment]
makes sense, should i create an issue to collect everyones ideas first?

**Comment by ashleygwilliams** [comment]
you could do it in a PR with this as a start?

**Comment by sup** [comment]
of course, hang on

**Pull request closed without merging**
