### PR TITLE
More member's list updates

### PR DESCRIPTION
**Pull request by nebrius**
Few more tweaks. Let's let this sit a few days before merging.

### CODE REVIEW

**Comment by Fishrock123** [comment]
@nebrius https://github.com/nodejs/inclusivity/issues/148

**Comment by nebrius** [comment]
Updated, thanks @Fishrock123

**Comment by nebrius** [comment]
I think this is ready to land now, things seem to have settled. If this looks good, can we go ahead and merge it?

**Comment by Lac** [comment]
LGTM :(

**Pull request merged**
