### PR TITLE
add infos about helping out

### PR DESCRIPTION
**Pull request by sup**
sry for the PRs in quick succession, i just had the idea that we might as well tell people where to start when wanting to contribute to the project. the lines i added are only a draft, feel free to correct my wording or something!

### CODE REVIEW

**Comment by sup** [comment]
wait, do inline issue links even work in readme markup?

**Comment by ashleygwilliams** [comment]
hey @sup ... i *really* dig this idea. a few things

- inline issues don't work in readme markup -__- (see preview here: https://github.com/sup/diversity/blob/patch-3/README.md)
- let's hold off on this, i'm gonna be closing that charter PR and starting a new one, so the link would need to be updated. maybe later today?
- i also like the idea of pointing to a few other "longterm" issues. we could talk about this later today.

**Comment by sup** [comment]
@ashleygwilliams sure, just ping me when you're ready!

**Comment by ashleygwilliams** [comment]
yar. remind me what your timezone is, @sup ? (so i dont ping at some ridiculous hour)

**Comment by sup** [comment]
i'm in CET, so i'll be up until ~5pm EST (which i think is your timezone, if i read correctly)

**Comment by ashleygwilliams** [comment]
yup!

**Comment by sup** [comment]
(ping @ashleygwilliams)

**Comment by nebrius** [comment]
I like @ashleygwilliams idea of adding longterm issues, although perhaps we could do that in a separate PR?

I think it could be handy to get this link up soon, as it provides at least some funnel for people just stopping by.

What do you think @ashleygwilliams?

**Comment by sup** [comment]
just realized i deleted my fork, so we're gonna have to open a new pr anyways -_-

**Pull request closed without merging**
