### PR TITLE
Add 2016-01-08 meeting notes

### PR DESCRIPTION
**Pull request by beaugunderson**

### CODE REVIEW

**Comment by beaugunderson** [comment]
(Oops need to fix markdown formatting; hold)

**Comment by sup** [comment]
(i think you've done this before by request) but make the TASKs bold? :P

**Comment by beaugunderson** [comment]
@sup that was part of the formatting, done now :)

**Comment by ashleygwilliams** [comment]
needs link to video -- once we add that i'm happy to merge :)

**Comment by beaugunderson** [comment]
@ashleygwilliams done!

**Pull request merged**
