### PR TITLE
Added "religion or lack thereof" to CoC

### PR DESCRIPTION
**Pull request by nebrius**
Oh, looks like there was a trailing whitespace my editor auto-removed. I can revert that, if people care.

### CODE REVIEW

**Comment by zkat** [comment]
LGTM

**Comment by ashleygwilliams** [comment]
LGTM- shall i merge?

**Comment by nebrius** [comment]
@ashleygwilliams go for it!

**Comment by chriseppstein** [comment]
:+1: Thanks!

**Comment by ashleygwilliams** [comment]
thanks for the suggestion @chriseppstein !!

**Pull request merged**
