### PR TITLE
refer to comm-comm

### PR DESCRIPTION
**Pull request by Trott**
Remove the README content and replace with a reference to the Community Committee. We don't want to people to think this WG is still active when it is not.

@nodejs/inclusivity @nodejs/tsc @nodejs/community-committee

### CODE REVIEW

**Comment by williamkapke** [comment]
Point of correction for anyone that comes along and reads this:

`Community Committee !== Inclusivity Working Group`

The Community Committee is working towards supporting the Inclusivity work as **one of** its efforts.

I don't think working in this change is the correct thing to say- maybe just add the text like the `collaboration` repo:

https://github.com/nodejs/collaboration
```
***ARCHIVE*: This repository is no longer active. Please see the the
[Community Committee](https://github.com/nodejs/community-committee) repository for 
information on current efforts around supporting and growing  the Node.js Community.**
```

**Comment by Trott** [comment]
@williamkapke I've updated the text to be the text you suggested.

**Comment by williamkapke** [comment]
k. Cool.

Thanks for doing this!

**Review by bnoordhuis — APPROVED** [review]

**Review by thefourtheye — APPROVED** [review]

**Review by nebrius — APPROVED** [review]

**Comment by hackygolucky** [comment]
@bnoordhuis @thefourtheye @nebrius @williamkapke how do y'all feel about renaming this repo nodejs/archived-inclusivity? There are plans to reboot inclusivity but the idea was to first get a much larger representation and perspective of folks with establishing CommComm and building from scratch the Inclusivity WG under CommComm scope. We don't want to blow away the history of the old repo if anyone would care to reference it, but I think we want to make it clear it is an almost entirely new effort when it is established.

**Comment by nebrius** [comment]
SGTM

**Comment by Trott** [comment]
I'm not sure if you can reuse a name that a different repository has previously used in your org. Might be worth checking and/or contemplating if that will be an issue. (Like, rename `inclusivity` -> `archived-inclusivity` is no problem, but you can't create a new `inclusivity` then, I don't *think*. Anyone know? I think you *might* be able to rename `archived-inclusivity` back to `inclusivity` though and maybe continue on from there?)

**Comment by hackygolucky** [comment]
@Trott well crap, I guess we'll cross that bridge when we get to it. We can try it, and worst case -have- to use the old repo but pull a major rewrite on the language and content. I'd really like to not do that, though. We'll bikeshed new repo name, maybe?

**Comment by Trott** [comment]
@hackygolucky Hopefully I'm wrong, but I feel like it's a feature to avoid people pulling or pushing from the wrong repo. (But maybe it does something smart like renames the git endpoint to be different somehow? I guess one of us can test the theory with our own personal GitHub account repos if we can't find the answer online.)

**Comment by williamkapke** [comment]
It worked ok on our test org:
(old) https://github.com/TestOrgPleaseIgnore/nodejs.org-archive
(new) https://github.com/TestOrgPleaseIgnore/nodejs.org

**Comment by Trott** [comment]
> It worked ok on our test org:

Hooray! I created a bunch of noise for nothing. Thanks for testing, @williamkapke!

**Pull request closed without merging**
