### PR TITLE
Updated license years

### PR DESCRIPTION
**Pull request by nebrius**
I removed the years from copyrights to match the main Node.js repo, and added a missing license to one of the meetings.

### CODE REVIEW

**Comment by sup** [comment]
LGTM

**Comment by ashleygwilliams** [comment]
ugh i was too quick on the :gun: last time :sob: my bad.
i'm gonna LGTM but wait for @scottgonzalez to check :wink:

**Comment by scottgonzalez** [comment]
Looks good.

**Comment by ashleygwilliams** [comment]
ok, merging.

**Pull request merged**
